# Xcode project fix-ups for a Godot iOS export that links NoctuaSDK via CocoaPods.
#
# Loaded by the Podfile that setup_xcode.sh generates and run from its
# post_integrate hook, so CocoaPods' bundled Xcodeproj gem is available.
# Every step is idempotent — re-running `pod install` is safe.

module NoctuaXcodeProject
  MIN_IOS_VERSION = '15.0'

  # Build settings Godot writes on the app target that would otherwise hide the
  # values CocoaPods provides through the target's base xcconfig.
  INHERITED_SETTINGS = %w[
    OTHER_LDFLAGS
    FRAMEWORK_SEARCH_PATHS
    LIBRARY_SEARCH_PATHS
    HEADER_SEARCH_PATHS
    GCC_PREPROCESSOR_DEFINITIONS
  ].freeze

  # Godot exports search "$(PROJECT_DIR)/**" recursively. Once Pods/ exists that
  # sweeps in every pod's device-only xcframework slice and breaks linking, so
  # recursion is limited to the app folder Godot copies plugin binaries into.
  RECURSIVE_PROJECT_PATH = '$(PROJECT_DIR)/**'
  SEARCH_PATH_SETTINGS = [
    'FRAMEWORK_SEARCH_PATHS',
    'FRAMEWORK_SEARCH_PATHS[arch=*]',
    'LIBRARY_SEARCH_PATHS',
    'LIBRARY_SEARCH_PATHS[arch=*]',
    'HEADER_SEARCH_PATHS'
  ].freeze

  SWIFT_SUPPORT_FILE = 'NoctuaSwiftSupport.swift'

  module_function

  # project_path: the exported .xcodeproj; resources: absolute paths of files
  # to add to the app bundle (noctuagg.json, GoogleService-Info.plist).
  def configure(project_path:, target_name:, resources:)
    project = Xcodeproj::Project.open(project_path)
    target = project.targets.find { |t| t.name == target_name }
    raise "NoctuaXcodeProject: target '#{target_name}' not found in #{project_path}" if target.nil?

    target.build_configurations.each do |config|
      scope_recursive_search_paths(config, target_name)
      inherit_pod_settings(config)
      raise_deployment_target(config)
    end
    project.build_configurations.each do |config|
      scope_recursive_search_paths(config, target_name)
      raise_deployment_target(config)
    end

    group = app_group(project, target_name)
    resources.each { |path| add_bundle_resource(project, target, group, path) }
    ensure_swift_runtime(project, target, group)

    project.save
  end

  def scope_recursive_search_paths(config, app_folder)
    SEARCH_PATH_SETTINGS.each do |key|
      value = config.build_settings[key]
      next if value.nil?

      values = value.is_a?(Array) ? value : value.split(' ')
      next unless values.include?(RECURSIVE_PROJECT_PATH)

      scoped = values.flat_map do |path|
        path == RECURSIVE_PROJECT_PATH ? ['$(PROJECT_DIR)', "$(PROJECT_DIR)/#{app_folder}/**"] : [path]
      end
      config.build_settings[key] = scoped.uniq
    end
  end

  def inherit_pod_settings(config)
    INHERITED_SETTINGS.each do |key|
      value = config.build_settings[key]
      next if value.nil?

      values = value.is_a?(Array) ? value : value.split(' ')
      next if values.include?('$(inherited)')

      config.build_settings[key] = ['$(inherited)'] + values
    end
  end

  def raise_deployment_target(config)
    current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
    return if current && Gem::Version.new(current) >= Gem::Version.new(MIN_IOS_VERSION)

    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = MIN_IOS_VERSION
  end

  # The group Godot creates for the app's own files (named after the target).
  def app_group(project, target_name)
    project.main_group.children.find { |g| g.respond_to?(:display_name) && g.display_name == target_name } ||
      project.main_group
  end

  def add_bundle_resource(project, target, group, path)
    name = File.basename(path)
    already_added = target.resources_build_phase.files_references.any? { |ref| ref && ref.display_name == name }
    return if already_added

    ref = group.files.find { |f| f.display_name == name } ||
          group.new_reference(relative_to_project(project, path))
    ref.source_tree = 'SOURCE_ROOT'
    target.resources_build_phase.add_file_reference(ref)
  end

  # NoctuaSDK is Swift. Godot 4.2+ exports already compile a dummy.swift; Godot 3.x
  # exports do not, so add an empty Swift file to make Xcode link the Swift runtime.
  def ensure_swift_runtime(project, target, group)
    has_swift = target.source_build_phase.files_references.any? { |ref| ref&.path.to_s.end_with?('.swift') }
    unless has_swift
      path = File.join(File.dirname(project.path.to_s), SWIFT_SUPPORT_FILE)
      File.write(path, "// Links the Swift runtime required by NoctuaSDK. Generated by setup_xcode.sh.\nimport Foundation\n")
      ref = group.new_reference(relative_to_project(project, path))
      ref.source_tree = 'SOURCE_ROOT'
      target.source_build_phase.add_file_reference(ref)
    end

    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] ||= '5.0'
    end
  end

  def relative_to_project(project, path)
    Pathname.new(path).relative_path_from(Pathname.new(File.dirname(project.path.to_s))).to_s
  end
end
