#!/usr/bin/env bash
# Links NoctuaSDK into a Godot iOS export with CocoaPods.
#
# Run after every Godot iOS export (tick "Export Project Only" in the iOS preset):
#   sdk/ios-plugin/scripts/setup_xcode.sh <exported-xcode-dir> <godot-project-dir>
# then open <name>.xcworkspace (not the .xcodeproj) to build and run.
#
# What it does:
#   1. copies noctuagg.json (required) and GoogleService-Info.plist (optional)
#      from the Godot project into the export and adds them to the app bundle;
#   2. writes a Podfile pinning NoctuaSDK $NOCTUA_IOS_SDK_VERSION;
#   3. runs `pod install`, whose post_integrate hook applies
#      noctua_xcode_project.rb (build-setting inheritance, iOS 15 minimum,
#      Swift runtime for Godot 3.x exports).
#
# Environment:
#   NOCTUA_IOS_SDK_VERSION  NoctuaSDK pod version (default below)
#   NOCTUA_IOS_SUBSPECS     space-separated NoctuaSDK subspecs to install
#   NOCTUA_SKIP_POD_INSTALL=1  write the Podfile only

set -euo pipefail

readonly DEFAULT_SDK_VERSION="0.40.1"
readonly DEFAULT_SUBSPECS="NoctuaInternalSDK Adjust FirebaseAnalytics FirebaseCrashlytics FirebaseMessaging FirebaseRemoteConfig FacebookSDK"

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SDK_VERSION="${NOCTUA_IOS_SDK_VERSION:-$DEFAULT_SDK_VERSION}"
readonly SUBSPECS="${NOCTUA_IOS_SUBSPECS:-$DEFAULT_SUBSPECS}"

fail() {
	echo "error: $*" >&2
	exit 1
}

[[ $# -eq 2 ]] || fail "usage: $0 <exported-xcode-dir> <godot-project-dir>"
[[ -d "$1" ]] || fail "export directory not found: $1"
[[ -d "$2" ]] || fail "Godot project directory not found: $2"
readonly EXPORT_DIR="$(cd "$1" && pwd)"
readonly GODOT_DIR="$(cd "$2" && pwd)"

find_xcodeproj() {
	local projects=()
	while IFS= read -r project; do projects+=("$project"); done < <(find "$EXPORT_DIR" -maxdepth 1 -name "*.xcodeproj" -not -name "Pods.xcodeproj")
	[[ ${#projects[@]} -eq 1 ]] || fail "expected exactly one .xcodeproj in $EXPORT_DIR, found ${#projects[@]}"
	echo "${projects[0]}"
}

readonly XCODEPROJ="$(find_xcodeproj)"
readonly APP_NAME="$(basename "$XCODEPROJ" .xcodeproj)"

copy_resources() {
	[[ -f "$GODOT_DIR/noctuagg.json" ]] || fail "noctuagg.json not found in $GODOT_DIR — the SDK cannot start without it"
	cp "$GODOT_DIR/noctuagg.json" "$EXPORT_DIR/"
	RESOURCES=("$EXPORT_DIR/noctuagg.json")

	if [[ -f "$GODOT_DIR/GoogleService-Info.plist" ]]; then
		cp "$GODOT_DIR/GoogleService-Info.plist" "$EXPORT_DIR/"
		RESOURCES+=("$EXPORT_DIR/GoogleService-Info.plist")
	else
		echo "warning: GoogleService-Info.plist not found in $GODOT_DIR — Firebase will not start" >&2
	fi
}

write_podfile() {
	local podfile="$EXPORT_DIR/Podfile"
	if [[ -f "$podfile" ]] && ! grep -q "noctua-godot-sdk" "$podfile"; then
		fail "$podfile exists and was not generated by this script — remove it or merge by hand"
	fi

	cp "$SCRIPT_DIR/noctua_xcode_project.rb" "$EXPORT_DIR/"

	local pod_lines="  pod 'NoctuaSDK', '$SDK_VERSION'"
	for subspec in $SUBSPECS; do
		pod_lines+=$'\n'"  pod 'NoctuaSDK/$subspec', '$SDK_VERSION'"
	done

	local resource_list=""
	for resource in "${RESOURCES[@]}"; do
		resource_list+="'${resource//"'"/"\\'"}', "
	done

	cat >"$podfile" <<PODFILE
# Generated by noctua-godot-sdk ios-plugin/scripts/setup_xcode.sh — re-run the
# script instead of editing; it is regenerated on every Godot export.
require_relative 'noctua_xcode_project'

platform :ios, NoctuaXcodeProject::MIN_IOS_VERSION
source 'https://cdn.cocoapods.org/'

project '$APP_NAME.xcodeproj'
use_frameworks!

target '$APP_NAME' do
$pod_lines
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      NoctuaXcodeProject.raise_deployment_target(config)
    end
  end
end

post_integrate do |_installer|
  NoctuaXcodeProject.configure(
    project_path: File.join(__dir__, '$APP_NAME.xcodeproj'),
    target_name: '$APP_NAME',
    resources: [${resource_list%, }]
  )
end
PODFILE
}

main() {
	command -v pod >/dev/null 2>&1 || fail "CocoaPods not found — install with: brew install cocoapods"
	export LANG="${LANG:-en_US.UTF-8}"

	# Keep Godot from importing the export (Pods/, copied config) when it
	# lives inside the game project, e.g. res://build/ios.
	touch "$EXPORT_DIR/.gdignore"

	copy_resources
	write_podfile
	echo "Podfile written for $APP_NAME (NoctuaSDK $SDK_VERSION: core $SUBSPECS)"

	if [[ "${NOCTUA_SKIP_POD_INSTALL:-0}" == "1" ]]; then
		return
	fi
	(cd "$EXPORT_DIR" && pod install)
	echo
	echo "Done. Open $EXPORT_DIR/$APP_NAME.xcworkspace in Xcode to build and run."
}

main
